import { Quiz, UserProfile } from '../../types';

export const INITIAL_USERS: (UserProfile & { passwordHash?: string })[] = [
  {
    uid: 'user-super-admin-01',
    email: 'admin@studentstudy.edu',
    displayName: 'Quản Trị Viên Hệ Thống',
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    department: 'Ban Giám Hiệu & CNTT',
    phone: '0901234567',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2025-01-01').toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    createdBy: 'SYSTEM_BOOTSTRAP',
  },
  {
    uid: 'user-admin-02',
    email: 'quanly@studentstudy.edu',
    displayName: 'Nguyễn Thị Thu Hà',
    role: 'ADMIN',
    status: 'ACTIVE',
    department: 'Phòng Đào Tạo',
    phone: '0908889999',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2025-01-10').toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    createdBy: 'user-super-admin-01',
  },
  {
    uid: 'user-teacher-01',
    email: 'teacher@studentstudy.edu',
    displayName: 'ThS. Trần Văn Minh',
    role: 'TEACHER',
    status: 'ACTIVE',
    department: 'Khoa Công Nghệ Thông Tin',
    phone: '0912345678',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2025-02-01').toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    createdBy: 'user-admin-02',
  },
  {
    uid: 'user-player-01',
    email: 'student01@studentstudy.edu',
    displayName: 'Lê Hoàng Long',
    role: 'PLAYER',
    status: 'ACTIVE',
    department: 'Lớp CNTT K21A',
    phone: '0987654321',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2025-02-15').toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    createdBy: 'user-admin-02',
  },
  {
    uid: 'user-player-02',
    email: 'student02@studentstudy.edu',
    displayName: 'Vũ Ngọc Mai',
    role: 'PLAYER',
    status: 'ACTIVE',
    department: 'Lớp CNTT K21B',
    phone: '0987654322',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    createdAt: new Date('2025-02-15').toISOString(),
    updatedAt: new Date().toISOString(),
    lastLoginAt: new Date().toISOString(),
    createdBy: 'user-admin-02',
  },
];

export const INITIAL_QUIZZES: Quiz[] = [
  {
    id: 'quiz-web-dev-01',
    title: 'Lập Trình Web Hiện Đại: Next.js 15, React 19 & TypeScript',
    description: 'Bộ câu hỏi toàn diện về cấu trúc Server Components, Hook React 19, Server Actions và tối ưu hiệu năng.',
    ownerId: 'user-teacher-01',
    ownerName: 'ThS. Trần Văn Minh',
    category: 'Công nghệ thông tin',
    tags: ['Next.js', 'React', 'TypeScript', 'Web Architecture'],
    difficulty: 'MEDIUM',
    coverImageUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&auto=format&fit=crop&q=80',
    visibility: 'PUBLIC',
    status: 'PUBLISHED',
    playCount: 142,
    questionCount: 5,
    createdAt: '2025-02-10T08:00:00.000Z',
    updatedAt: '2025-03-01T10:00:00.000Z',
    questions: [
      {
        id: 'q-web-01',
        quizId: 'quiz-web-dev-01',
        type: 'MULTIPLE_CHOICE',
        question: 'Trong Next.js App Router, mặc định tất cả các component bên trong thư mục `app/` là loại component nào?',
        options: [
          'React Server Components (RSC)',
          'Client Components',
          'Static Pure Components',
          'Higher-Order Components'
        ],
        correctAnswer: 0,
        explanation: 'Next.js App Router sử dụng React Server Components làm mặc định để giảm bundle size gửi về client và render trực tiếp trên server.',
        points: 100,
        timeLimit: 20,
        order: 1,
      },
      {
        id: 'q-web-02',
        quizId: 'quiz-web-dev-01',
        type: 'TRUE_FALSE',
        question: 'Thư viện Firebase Admin SDK có thể được import và thực thi an toàn trực tiếp bên trong React Client Component.',
        options: ['Đúng', 'Sai'],
        correctAnswer: 1,
        explanation: 'Sai! Firebase Admin SDK chứa private key và quyền quản trị toàn diện, chỉ được phép import và chạy ở server-side (Node.js runtime / Route Handlers).',
        points: 100,
        timeLimit: 15,
        order: 2,
      },
      {
        id: 'q-web-03',
        quizId: 'quiz-web-dev-01',
        type: 'MULTIPLE_SELECT',
        question: 'Những tính năng nào sau đây là đặc điểm mới nổi bật của React 19?',
        options: [
          'Actions và useActionState hook',
          'Tích hợp native Document Metadata (<title>, <meta>)',
          'Hỗ trợ ref trực tiếp như một prop thông thường',
          'Bắt buộc dùng Class Component cho lifecycle'
        ],
        correctAnswer: [0, 1, 2],
        explanation: 'React 19 giới thiệu Actions, useActionState, Asset Loading, Document Metadata native, và cho phép truyền ref trực tiếp như prop mà không cần forwardRef.',
        points: 150,
        timeLimit: 25,
        order: 3,
      },
      {
        id: 'q-web-04',
        quizId: 'quiz-web-dev-01',
        type: 'IMAGE_QUESTION',
        imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
        question: 'Mô hình lập trình bất đồng bộ nào trong TypeScript đảm bảo type safety mạnh mẽ nhất cho dữ liệu trả về từ API?',
        options: [
          'Sử dụng Generics kết hợp Schema Validation (Zod/Typebox)',
          'Sử dụng kiểu dữ liệu `any` để linh hoạt',
          'Bỏ qua ép kiểu ở biên giới client-server',
          'Sử dụng eval() để parse JSON động'
        ],
        correctAnswer: 0,
        explanation: 'Generics kết hợp Runtime validation (Zod) cho phép kiểm tra schema ở runtime và tự động suy luận kiểu tĩnh an toàn.',
        points: 120,
        timeLimit: 20,
        order: 4,
      },
      {
        id: 'q-web-05',
        quizId: 'quiz-web-dev-01',
        type: 'MULTIPLE_CHOICE',
        question: 'Trong cơ chế Realtime Multiplayer, tại sao Realtime Database thường được ưu tiên hơn Cloud Firestore cho việc đồng bộ tọa độ & thời gian thực?',
        options: [
          'Độ trễ thấp hơn (sub-100ms) và mô hình socket connection liên tục giá rẻ hơn cho các thao tác ghi liên tục',
          'Firestore không hỗ trợ lưu JSON',
          'Realtime Database không cần kết nối mạng',
          'Realtime Database có dung lượng lưu trữ lớn hơn 100 lần'
        ],
        correctAnswer: 0,
        explanation: 'Realtime Database duy trì WebSocket liên tục với độ trễ siêu thấp, tính phí theo dung lượng tải truyền tải (GB) thay vì tính phí theo số lượt document write như Firestore.',
        points: 100,
        timeLimit: 20,
        order: 5,
      },
    ],
  },
  {
    id: 'quiz-science-ai-02',
    title: 'Kiến Trúc Trí Tuệ Nhân Tạo & Mô Hình Ngôn Ngữ Lớn (LLM)',
    description: 'Thử thách kiến thức về Attention Mechanism, Gemini multimodal, Vector Embeddings và RAG.',
    ownerId: 'user-teacher-01',
    ownerName: 'ThS. Trần Văn Minh',
    category: 'Khoa học & Trí tuệ nhân tạo',
    tags: ['AI', 'Gemini', 'Machine Learning', 'RAG'],
    difficulty: 'HARD',
    coverImageUrl: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=80',
    visibility: 'PUBLIC',
    status: 'PUBLISHED',
    playCount: 98,
    questionCount: 4,
    createdAt: '2025-02-18T14:00:00.000Z',
    updatedAt: '2025-03-02T09:30:00.000Z',
    questions: [
      {
        id: 'q-ai-01',
        quizId: 'quiz-science-ai-02',
        type: 'MULTIPLE_CHOICE',
        question: 'Cơ chế cốt lõi nào trong kiến trúc Transformer cho phép mô hình đánh giá mức độ quan trọng giữa các từ trong chuỗi văn bản?',
        options: [
          'Self-Attention Mechanism',
          'Convolutional Filter 3x3',
          'Recurrent Hidden Loop',
          'Max Pooling Operation'
        ],
        correctAnswer: 0,
        explanation: 'Cơ chế Self-Attention cho phép mỗi token tương tác và gán trọng số liên hệ với tất cả các token khác trong ngữ cảnh.',
        points: 100,
        timeLimit: 20,
        order: 1,
      },
      {
        id: 'q-ai-02',
        quizId: 'quiz-science-ai-02',
        type: 'TRUE_FALSE',
        question: 'Mô hình Multimodal có khả năng xử lý đồng thời nhiều loại dữ liệu như văn bản, hình ảnh, âm thanh và mã nguồn.',
        options: ['Đúng', 'Sai'],
        correctAnswer: 0,
        explanation: 'Đúng! Các mô hình multimodal hiện đại (như Gemini) được huấn luyện từ đầu trên nhiều phương thức dữ liệu khác nhau.',
        points: 80,
        timeLimit: 15,
        order: 2,
      },
      {
        id: 'q-ai-03',
        quizId: 'quiz-science-ai-02',
        type: 'MULTIPLE_CHOICE',
        question: 'Kỹ thuật RAG (Retrieval-Augmented Generation) giải quyết vấn đề cốt lõi nào của LLM?',
        options: [
          'Giảm thiểu ảo giác (hallucination) bằng cách truy xuất dữ liệu thực tế cập nhật',
          'Tăng tốc độ kết xuất hình ảnh 3D',
          'Loại bỏ hoàn toàn sự phụ thuộc vào GPU',
          'Biến mô hình ngôn ngữ thành hệ điều hành'
        ],
        correctAnswer: 0,
        explanation: 'RAG truy vấn các tài liệu liên quan từ vector database và cung cấp làm ngữ cảnh cho LLM, giảm thiểu việc mô hình bịa đặt thông tin.',
        points: 120,
        timeLimit: 20,
        order: 3,
      },
      {
        id: 'q-ai-04',
        quizId: 'quiz-science-ai-02',
        type: 'MULTIPLE_SELECT',
        question: 'Những phương pháp nào sau đây giúp kiểm soát chất lượng phản hồi từ các mô hình AI?',
        options: [
          'Thiết lập System Instructions rõ ràng',
          'Cung cấp Few-shot examples mẫu',
          'Sử dụng Structured Outputs (JSON Schema)',
          'Tăng độ dài văn bản vô hạn mà không cần cấu trúc'
        ],
        correctAnswer: [0, 1, 2],
        explanation: 'System prompts, few-shot examples và structured schema constraint là 3 kỹ thuật hàng đầu để tạo ra phản hồi AI đáng tin cậy.',
        points: 150,
        timeLimit: 25,
        order: 4,
      },
    ],
  },
  {
    id: 'quiz-english-comm-03',
    title: 'Tiếng Anh Giao Tiếp Học Thuật & Công Sở (IELTS 6.5+)',
    description: 'Từ vựng chuyên ngành, cấu trúc diễn đạt tự nhiên và phản xạ nhanh cho sinh viên.',
    ownerId: 'user-teacher-01',
    ownerName: 'ThS. Trần Văn Minh',
    category: 'Ngoại ngữ',
    tags: ['English', 'Communication', 'Vocabulary', 'IELTS'],
    difficulty: 'EASY',
    coverImageUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800&auto=format&fit=crop&q=80',
    visibility: 'PUBLIC',
    status: 'PUBLISHED',
    playCount: 215,
    questionCount: 4,
    createdAt: '2025-01-20T10:00:00.000Z',
    updatedAt: '2025-02-28T16:00:00.000Z',
    questions: [
      {
        id: 'q-eng-01',
        quizId: 'quiz-english-comm-03',
        type: 'MULTIPLE_CHOICE',
        question: 'Choose the most professional phrase: "We need to ______ this meeting until next Monday due to an urgent conflict."',
        options: [
          'postpone / reschedule',
          'kill',
          'throw away',
          'slow down'
        ],
        correctAnswer: 0,
        explanation: '"Postpone" hoặc "reschedule" là từ ngữ lịch sự, chuẩn mực trong giao tiếp học thuật và công sở.',
        points: 100,
        timeLimit: 15,
        order: 1,
      },
      {
        id: 'q-eng-02',
        quizId: 'quiz-english-comm-03',
        type: 'MULTIPLE_CHOICE',
        question: 'What is the synonym of "Metaphorical"?',
        options: ['Symbolic / Figurative', 'Literal / Word-for-word', 'Accidental', 'Musical'],
        correctAnswer: 0,
        explanation: '"Metaphorical" nghĩa là mang tính ẩn dụ, tượng trưng (symbolic, figurative).',
        points: 100,
        timeLimit: 15,
        order: 2,
      },
      {
        id: 'q-eng-03',
        quizId: 'quiz-english-comm-03',
        type: 'TRUE_FALSE',
        question: 'The idiom "Touch base" means to briefly make contact or communicate with someone.',
        options: ['True', 'False'],
        correctAnswer: 0,
        explanation: 'True! "Let\'s touch base tomorrow morning" means let\'s connect briefly to update information.',
        points: 100,
        timeLimit: 15,
        order: 3,
      },
      {
        id: 'q-eng-04',
        quizId: 'quiz-english-comm-03',
        type: 'MULTIPLE_CHOICE',
        question: 'Select the best phrase to politely disagree in a formal discussion:',
        options: [
          '"I see your point, however, another perspective to consider is..."',
          '"You are completely wrong about everything."',
          '"Never say that again in this boardroom."',
          '"Whatever you say does not matter."'
        ],
        correctAnswer: 0,
        explanation: 'Polite disagreement acknowledges the other point of view first before introducing an alternative perspective.',
        points: 100,
        timeLimit: 20,
        order: 4,
      },
    ],
  },
];
